calculator/urls.py
from django.conf.urls import url

from . import views

app_name = 'calculator'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^result/$', views.result, name='result'),
    #url(r'^total/$', views.totalvote, name='totalvote'),
    
]

test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^calculator/', include('calculator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'calculator.views.home'),
    
]

calculator/models.py
from django.db import models

# Create your models here.

calculator/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request,'calculator/home.html')

def result(request):
    num1 = int(request.POST['input1'])
    num2 = int(request.POST['input2'])
    operator = request.POST['enter']
    answer = ''
    if operator == '+':
        answer = num1 + num2 
    if operator == '-':
        answer = num1 - num2
    if operator == '*':
        answer = num1 * num2
    if operator == '/':
        answer = num1 / num2
        
          
    return render(request, 'calculator/result.html',{'num1':num1,'num2':num2,'operator':operator,'answer':answer})

calculator/templates/calculator/cal.html
<html>
<head>
 <title>simple calculator</title>
 </head>
 <body>
 <h2>simple calculaotor using django</h2> 

<form action="/" method="post">
 Number 1: <input type="text" name="num1"> 
 Number 2: <input type="text" name="num2" />
<input type="submit" name= "op" value="+" />
<input type="submit" name= "op" value="-" />
<input type="submit" name= "op" value="*" />
<input type="submit" name= "op" value="/" />


</form>

</body>
</html>

calculator/templates/calculator/home.html
<html>
	<head>
		<title>Calculate</title>
		<meta charset="utf-8"/>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'calculator/main.css' %}">	
	</head>
	<body>		
		<h1><center><div class="ex1">Calculator app</div></center></h1>
			<form action="{% url 'calculator:result' %}" method='POST'>
				{% csrf_token %}
				Number 1:<input type="text" name="input1" />
				Number 2:<input type="text" name="input2"/>
				<input type="radio" name="enter" value="+" checked> plus
				<input type="radio" name="enter" value="-" checked> minus
				<input type="radio" name="enter" value="*" checked> multiply
				<input type="radio" name="enter" value="/" checked> devide
				<input class="submit1" type="submit" name="method" value="submit"/>
			</form>
	</body>
</html>

calculator/templates/calculator/index.html
<h1>Homepage</h1>

<a href="/admin/">Admin</a><br>

calculator/templates/calculator/result.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Result</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'calculator/result.css' %}">

	</head>
	<body>
		<h1><center><div class="ex1">Result</div></center></h1>
		<h1><p>{{num1}} {{operator}} {{num2}} = {{answer}}</p></h1>
	</body>
</html>

<p><a class="linkhover" href="{% url 'calculator:home' %}" >BACK</a></p>